import type { ParsedFile } from './parse.ts';
import type { Config } from './config.ts';

export interface EntrySource {
    value: string;
    sourceFile: string;
}

export function collectEntries(files: ParsedFile[]): Map<string, EntrySource> {
    const map = new Map<string, EntrySource>();
    for (const file of files) {
        for (const line of file.lines) {
            if (line.type !== 'entry') continue;
            if (map.has(line.key)) {
                const existing = map.get(line.key)!;
                throw new Error(
                    `Duplicate key "${line.key}" found in:\n  - ${existing.sourceFile}\n  - ${file.path}`,
                );
            }
            map.set(line.key, { value: line.value, sourceFile: file.path });
        }
    }
    return map;
}

export function validateStructure(
    refFiles: ParsedFile[],
    targetFiles: ParsedFile[],
    targetLocale: string,
): void {
    const refPaths = new Set(refFiles.map((f) => f.path));
    const targetPaths = new Set(targetFiles.map((f) => f.path));

    const missing = [...refPaths].filter((p) => !targetPaths.has(p));
    const extra = [...targetPaths].filter((p) => !refPaths.has(p));

    if (missing.length === 0 && extra.length === 0) return;

    const lines: string[] = [`Structure mismatch for locale "${targetLocale}":`];
    if (missing.length > 0) {
        lines.push(`  Missing files:\n${missing.map((p) => `    - ${p}`).join('\n')}`);
    }
    if (extra.length > 0) {
        lines.push(`  Extra files:\n${extra.map((p) => `    - ${p}`).join('\n')}`);
    }
    throw new Error(lines.join('\n'));
}

export function emitMerged(files: ParsedFile[], locale: string, config: Config): string {
    if (config.randomizeEntries) {
        const entries: Array<{ key: string; value: string }> = [];
        for (const file of files) {
            for (const line of file.lines) {
                if (line.type === 'entry') entries.push({ key: line.key, value: line.value });
            }
        }
        for (let i = entries.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [entries[i], entries[j]] = [entries[j], entries[i]];
        }
        return entries.map((e) => `${e.key}=${e.value}`).join('\n') + '\n';
    }

    const totalKeys = files.reduce(
        (sum, f) => sum + f.lines.filter((l) => l.type === 'entry').length,
        0,
    );
    const parts: string[] = [];

    if (!config.stripComments) {
        parts.push(
            `## ----------------------------------------------------------`,
            `## Auto-merged for ${locale}`,
            `## ${files.length} file(s), ${totalKeys} unique key(s)`,
            `## Generated by Rune`,
            `## ----------------------------------------------------------`,
            ``,
        );
    }

    for (const file of files) {
        if (!config.stripComments) {
            parts.push(`## --- ${file.path} ---`);
        }
        for (const line of file.lines) {
            if (line.type === 'entry') {
                parts.push(`${line.key}=${line.value}`);
            } else if (!config.stripComments) {
                if (line.type === 'comment') parts.push(line.text);
                else if (line.type === 'blank') parts.push(``);
            }
        }
        if (!config.stripComments) parts.push(``);
    }

    if (config.stripComments && parts.length > 0) parts.push(``);
    return parts.join('\n');
}
